[package]
name = "framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program-test = "1.16.9"
solana-program = "1.16.9"
solana-logger = "1.16.9"
solana-sdk = "1.16.9"
spl-token = { version = "4.0.0", features = [ "no-entrypoint" ]}
spl-associated-token-account = { version="2.0.0", features = [ "no-entrypoint" ] }
borsh = "0.9.3"
borsh-derive = "0.9.1"
chall = { path ="./chall" }
sol-ctf-framework = { git = "https://github.com/otter-sec/sol-ctf-framework", branch="rewrite-v2" }
threadpool = "1.8.1"